### ISSUE TITLE
Termination of executable due to wrong input file length.

### ISSUE THREAD

**Issue by nilsnevertree** [nilsnevertree/CLEO-sdm-eurec4a#22]
But when running the script, an error message from the executable is thrown.
The thermodynamic files are created as expected, and the same goes for the superdroplets.

Number of gridboxes for simplicity is ``3``
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  6 vector is not consistent with correct size 3
````

It seems the initial conditions are good though.

![gridboxboundaries](https://github.com/nilsnevertree/CLEO-sdm-eurec4a/assets/49751662/27a72f98-ca51-4309-a952-3b3f986a1294)

![thermo1dalltimeprofiles](https://github.com/nilsnevertree/CLEO-sdm-eurec4a/assets/49751662/b889b9c1-2b38-4900-a5ca-58e1d5f7bebe)

![initGBxs_distribs](https://github.com/nilsnevertree/CLEO-sdm-eurec4a/assets/49751662/903aa8b6-f7f5-48c6-ba69-8308045dc689)

**Comment by nilsnevertree** [comment]
Clara provided the solutino to this issue: Make sure that the 
``COUPLTSTEP`` $\leq$ ``T_END``.

````yaml

timesteps:
  CONDTSTEP: 0.1                                       # time between SD condensation [s]
  COLLTSTEP: 1                                         # time between SD collision [s]
  MOTIONTSTEP: 2                                       # time between SDM motion [s]
  COUPLTSTEP: 2400                                     # time between dynamic couplings [s]
  OBSTSTEP: 5                                          # time between SDM observations [s]
  T_END: 2400                                          # time span of integration from 0s to T_END [s]
````

**Comment by nilsnevertree** [comment]
Clara provided the solutino to this issue: Make sure that the 
``COUPLTSTEP`` $\leq$ ``T_END``.

````yaml

timesteps:
  CONDTSTEP: 0.1                                       # time between SD condensation [s]
  COLLTSTEP: 1                                         # time between SD collision [s]
  MOTIONTSTEP: 2                                       # time between SDM motion [s]
  COUPLTSTEP: 2400                                     # time between dynamic couplings [s]
  OBSTSTEP: 5                                          # time between SDM observations [s]
  T_END: 2400                                          # time span of integration from 0s to T_END [s]
````
